name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd SecretKey
          npm ci

      - name: Build Vite project
        run: |
          cd SecretKey
          npm run build

      - name: Copy output to root-level folder
        run: |
          mkdir -p dist-root
          cp -r SecretKey/dist/* dist-root/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-root
          publish_branch: gh-pages
